<?= $this->insert('overall/header') ?>
<body id="page-top" class="index">

  <?= $this->insert('overall/topnav') ?>

    <section id="about">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 text-center">
                    <h2>¡Hola!</h2>
                </div>
                <div class="col-sm-12 text-center">
                  <br />
                  <p>Bienvenido a Ocrend-Framework, <?= $this->url_amigable('ya puedes comenzar a programar') ?>.</p>
                </div>
            </div>
        </div>
    </section>

<?= $this->insert('overall/footer') ?>
</body>
</html>
