<?= $this->insert('overall/header') ?>
<body class="framework">

  <div class="logo">
    <h3><?= strtoupper(APP) ?></h3>
  </div>

  <div class="content">
    <div class="ocrend-welcome">
      <span class="ocrend-welcome">MVC PHP 7.</span>
      <span class="ocrend-welcome-subtitle">Para aprendices y expertos.</span>
    </div>
    <div class="form-actions">
      <?php if (!isset($_SESSION[SESS_APP_ID])): ?>
        <button type="button" data-toggle="modal" data-target="#iniciar_sesion" class="btn red btn-block">INICIAR SESIÓN</button>
        <button type="button" data-toggle="modal" data-target="#registro" class="btn red btn-block">REGISTRO</button>
      <?php else: ?>
        <div class="alert alert-success">
          Bienvenido usuario de <b>id <?= $_SESSION[SESS_APP_ID] ?></b>, ahora puedes <a style="color: #023b32!important;" href="logout/">cerrar sesión</a>
        </div>
      <?php endif ?>

      <div class="pull-left firewall-status-block">
        <span class="firewall-status">
          <?php if (FIREWALL): ?>
            <span class="label label-success">Firewall Activo</span>
          <?php else: ?>
            <span class="label label-danger">Firewall Inactivo</span>
          <?php endif ?>
        </span>
      </div>
      <div class="pull-right firewall-status-block">
        <span class="firewall-status">
          <?php if (DEBUG): ?>
            <span class="label label-success">Debug Activo</span>
          <?php else: ?>
            <span class="label label-danger">Debug Inactivo</span>
          <?php endif ?>
        </span>
      </div>

    </div>

    <?php if (!isset($_SESSION[SESS_APP_ID])): ?>
      <?= $this->insert('overall/register') ?>
      <?= $this->insert('overall/login') ?>
      <?= $this->insert('overall/lostpass') ?>
    <?php endif ?>

    <?= $this->insert('overall/footer') ?>

  </div>



</body>
</html>
