#!/usr/bin/env php
<?php

/*
 * This file is part of the Ocrend Framewok 3 package.
 *
 * (c) Ocrend Software <info@ocrend.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
*/

use Symfony\Component\Console\Application;
use Ocrend\Kernel\Generator\Commands as Command;

# Definir el path
define('___ROOT___', '');

# Iniciar la configuración
require ___ROOT___ . 'Ocrend/Kernel/Config/Config.php';

$info = new Command\Info;
$app = new Application();
$app->add(new Command\Usersinstall);
$app->add(new Command\Controller);
$app->add(new Command\Model);
$app->add(new Command\View);
$app->add($info);
$app->setDefaultCommand($info->getName());
$app->run();