<footer class="text-center">
    <div class="footer-above">
        <div class="container">
            <div class="row">
                <div class="footer-col col-md-4">
                    <h3>Requisitos</h3>
                    <p>PHP 7, Apache 2, MySQL 5</p>
                </div>
                <div class="footer-col col-md-4">
                    <h3>Documentación</h3>
                    <ul class="list-inline">
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-google-plus"></i></a>
                        </li>
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-youtube"></i></a>
                        </li>
                        <li>
                            <a href="https://github.com/prinick96/Ocrend-Framework/wiki" target="_blank" class="btn-social btn-outline"><i class="fa fa-fw fa-github"></i></a>
                        </li>
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-globe"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="footer-col col-md-4">
                    <h3>Módulos</h3>
                    <p>
                      Firewall : <span class="label label-<?= FIREWALL ? 'success">Activo' : 'danger">Apagado'?></span><br />
                      Debug: <span class="label label-<?= FIREWALL ? 'success">Activo' : 'danger">Apagado'?></span>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-below">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    Copyright &copy; <?= APP ?> <?= date('Y',time()) ?>
                </div>
            </div>
        </div>
    </div>
</footer>

<!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
<div class="scroll-top page-scroll hidden-sm hidden-xs hidden-lg hidden-md">
    <a class="btn btn-primary" href="#page-top">
        <i class="fa fa-chevron-up"></i>
    </a>
</div>

<!-- IMPORTANT FOR DEBUG MODE NO DELETE -->
<?php if (true == DEBUG): ?>
<script src="views/app/js/jdev.js"></script>
<?php else: ?>
<script src="views/app/js/jquery.js"></script>
<?php endif ?>
<!-- IMPORTANT FOR DEBUG MODE NO DELETE -->

<script src="views/app/js/jquery.numeric.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<?php if (!isset($_SESSION['app_id'])): ?>
<script src="views/app/js/login.js"></script>
<script src="views/app/js/register.js"></script>
<script src="views/app/js/lostpass.js"></script>
<?php endif ?>
<script>
  $('.numeric').numeric();
</script>
