
<div class="framework-options">
  <h4 class="pull-left">Documentación oficial</h4>
  <div class="pull-right documentacion">
    <a class="fa fa-youtube" href="https://www.youtube.com/playlist?list=PLDQZoQpLCoUBVbDUxr8cxVX0ik8uh5WBh" target="_blank"></a>
    <a class="fa fa-github"  href="https://github.com/prinick96/Ocrend-Framework/wiki" target="_blank"></a>
    <a class="fa fa-globe" href="http://framework.ocrend.com" target="_blank"></a>
  </div>
  </ul>
</div>

<!-- IMPORTANT FOR DEBUG MODE NO DELETE -->
<?php if (true == DEBUG): ?>
<script src="views/app/js/jdev.js"></script>
<?php else: ?>
<script src="views/app/js/jquery.js"></script>
<?php endif ?>
<!-- IMPORTANT FOR DEBUG MODE NO DELETE -->

<script src="views/app/js/jquery.numeric.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<?php if (!isset($_SESSION[SESS_APP_ID])): ?>
<script src="views/app/js/login.js"></script>
<script src="views/app/js/register.js"></script>
<script src="views/app/js/lostpass.js"></script>
<?php endif ?>
<script>
  $('.numeric').numeric();
</script>
