<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
       <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Navegación</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#page-top"><?= APP ?></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <?php if (!isset($_SESSION[SESS_APP_ID])): ?>
                  <li class="">
                      <a href="" data-toggle="modal" data-target="#iniciar_sesion">Iniciar Sesión</a>
                  </li>
                  <li class="">
                      <a href="" data-toggle="modal" data-target="#registro">Registro</a>
                  </li>
                <?php else: ?>
                  <li class="">
                      <a href="logout/">Cerrar Sesión id : <?= $_SESSION[SESS_APP_ID] ?></a>
                  </li>
                <?php endif ?>
            </ul>
        </div>
        <!--  /.navbar-collapse -->
    </div>
    <!--  /.container-fluid -->
</nav>

<?php if (!isset($_SESSION[SESS_APP_ID])): ?>
  <?= $this->insert('overall/register') ?>
  <?= $this->insert('overall/login') ?>
  <?= $this->insert('overall/lostpass') ?>
<?php endif ?>

<header>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <img class="img-responsive" src="http://ocrend.com/views/frontend/images/logo.png" alt="">
                <div class="intro-text">
                    <hr class="star-light">
                    <span class="skills">Ocrend Framework PHP 7</span>
                </div>
            </div>
        </div>
    </div>
</header>
