<!DOCTYPE html>
<html lang="es">
  <head>
    <base href="<?=  URL ?>" />
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="application-name" content="Ocrend Framework" />
    <meta name="author" content="www.ocrend.com" />
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://bootswatch.com/flatly/bootstrap.min.css" />
    <link rel="stylesheet" href="views/app/css/framework.css">

    <link rel="apple-touch-icon-precomposed" href="views/app/images/apple-touch-icon.png" />
    <link rel="shortcut icon" type="image/x-icon" href="views/favicon.ico" />

    <title><?= APP ?></title>
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
