<?= $this->insert('overall/header') ?>
<body class="framework">

  <div class="logo">
    <h3><?= strtoupper(APP) ?></h3>
  </div>

  <div class="content">
    <div class="ocrend-welcome">
      <span class="ocrend-welcome">¡404 ERROR!</span>
      <span class="ocrend-welcome-subtitle">Elemento no encontrado.</span>
    </div>
    <div class="form-actions">
      <p>Controlador <b><?= str_replace('Controller','',$controller) ?></b> no encontrado.</p>

      <?= $this->insert('overall/modules') ?>

    </div>

    <?= $this->insert('overall/footer') ?>

  </div>
</body>
</html>
