<?= $this->insert('overall/header') ?>
  <body>
    <div class="container">
      <div class="presentacion center">
        <div class="row">
          <div class="col-xs-12">
            <h1>Cambio de contraseña</h1>
          </div>
          <div class="col-xs-12 botones">
            <?php if (false == $pass) ?>
              <div class="alert alert-danger">¡Este enlace ha caducado!</div>
            <?php else: ?>
              <div class="alert alert-success">Tu nueva contraseña es <b><?= $pass ?></b> , puedes <a href="" style="color: #023b32!important;" data-toggle="modal" data-target="#iniciar_sesion">iniciar sesión</a></div>
            <?php endif ?>
          </div>
        </div>
      </div>
    </div>
    <?= $this->insert('overall/footer') ?>
  </body>
</html>
