<?= $this->insert('overall/header') ?>
<body class="framework">

  <div class="logo">
    <h3><?= strtoupper(APP) ?></h3>
  </div>

  <div class="content">
    <div class="ocrend-welcome">
      <span class="ocrend-welcome">Cambio de contraseña.</span>
      <span class="ocrend-welcome-subtitle">Solicitud de cambio.</span>
    </div>
    <div class="form-actions">

      <?php if (false === $pass): ?>
        <div class="alert alert-danger">¡Este enlace ha caducado!</div>
      <?php else: ?>
        <div class="alert alert-success">Tu nueva contraseña es <b><?= $pass ?></b> , puedes <a href="" style="color: #023b32!important;" data-toggle="modal" data-target="#iniciar_sesion">iniciar sesión</a></div>
      <?php endif ?>

      <?= $this->insert('overall/modules') ?>

    </div>

    <?= $this->insert('overall/footer') ?>

  </div>
</body>
</html>
